-- =========================================================
-- 表名：command
-- 说明：
--   设备下行指令表（后台/服务端 -> 设备）
--   设备通过轮询/长连接拉取待执行指令，执行后回写结果
--
-- 设计原则：
--   1) 命令是“任务队列”语义：pending -> sent -> done/failed/canceled
--   2) payload/result 用 jsonb，避免一开始想不全
--   3) created_at / updated_at 由 GORM 维护（DB 不加 trigger）
-- =========================================================

create extension if not exists pgcrypto;

create table if not exists command
(
    id          bigint generated by default as identity primary key,

    -- 设备 ID（逻辑外键，指向 device.id）
    device_id   bigint      not null,

    -- 命令类型（建议 smallint，代码里枚举）
    -- 示例：
    --   1=reboot
    --   2=set_config
    --   3=get_status
    --   4=calibrate_scale (校准/去皮/基线修正)
    --   5=screen_show (屏幕显示)
    --   6=tts_speak (语音播报)
    cmd_type    smallint    not null,

    -- 命令参数（结构可变）
    payload     jsonb       not null default '{}'::jsonb,

    -- 幂等 ID（可选）：用于防止重复下发同一命令
    request_id  uuid        not null default gen_random_uuid(),

    -- 状态：1=pending 2=sent 3=done 4=failed 5=canceled 6=expired
    status      smallint    not null default 1,

    -- 优先级（数值越小优先级越高，或你反过来也行）
    priority    smallint    not null default 100,

    -- 超时/过期时间：设备拉取时可忽略已过期命令
    expires_at  timestamptz,

    -- 设备侧执行回执
    -- done/failed 时由设备或服务端写入
    finished_at timestamptz,
    result      jsonb       not null default '{}'::jsonb,

    -- 审计字段（由 GORM 自动维护）
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),

    constraint command_status_ck check (status in (1, 2, 3, 4, 5, 6))
);

-- =========================================================
-- 索引：让设备“拉取待执行命令”非常快
-- =========================================================

-- 设备拉取：按 device_id + status + priority + created_at
create index if not exists command_fetch_idx
    on command (device_id, status, priority, created_at);

-- 幂等：同一 request_id 不重复
create unique index if not exists command_request_id_uk
    on command (request_id);

-- 清理/排障：按过期时间
create index if not exists command_expires_at_idx
    on command (expires_at);
