create table device
(
    id              bigint generated by default as identity
        primary key,
    device_uid      uuid                                          not null
        constraint device_public_id_uk
            unique,
    serial_no       text                                          not null
        constraint device_serial_no_uk
            unique,


    name            text,


    model           text,
    status          smallint                                      not null
        constraint device_status_ck
            check (status = ANY (ARRAY [0, 1, 2, 3])),
    power_mode      smallint
        constraint device_power_mode_ck
            check (power_mode = ANY (ARRAY [1, 2, 3])),


    hw_version      text,
    fw_version      text,

    claim_code      text                                          not null,
    claimed_at      timestamp with time zone,

    disabled_at     timestamp with time zone,
    disabled_reason text,
    retired_at      timestamp with time zone,
    retired_reason  text,

    last_seen_at    timestamp with time zone,
    last_error_at   timestamp with time zone,

    active_errors   text[]                   default '{}'::text[] not null,
    meta            jsonb                    default '{}'::jsonb  not null,

    created_at      timestamp with time zone default now()        not null,
    updated_at      timestamp with time zone default now()        not null
);

comment on column device.status is '设备状态: 0-预注册 1-激活 2-禁用 3-退役';

comment on column device.power_mode is '供电方式: 1-市电 2-太阳能 3-混合动力';

alter table device
    owner to postgres;

create index device_active_errors_gin_idx
    on device using gin (active_errors);

