-- =========================================================
-- 表名：event
-- 说明：
--   设备事件表（业务事实/审计日志）
--   用于记录：投递、开门/关门、称重结果、异常告警、维护操作等
--
-- 设计原则：
--   1) 写多读也多（后台查询/排障/导出），核心查询：device + time
--   2) 主键 bigint identity（索引友好）
--   3) 高频事实表不加外键（避免写入额外开销；设备删了事件仍有价值）
--   4) created_at / updated_at 由 GORM 维护（DB 不加 trigger）
--   5) 结构易变的详情放 payload(jsonb)
-- =========================================================

-- 若你项目里还没启用过 pgcrypto（用于 gen_random_uuid），保留这一行
create extension if not exists pgcrypto;

create table if not exists event
(
    -- 内部主键
    id          bigint generated by default as identity primary key,

    -- 设备 ID（逻辑外键，指向 device.id）
    device_id   bigint      not null,

    -- 事件实际发生时间（设备侧/业务侧认为的发生时间）
    -- 与 created_at(入库时间)区分，便于离线补报/网络抖动排障
    occurred_at timestamptz not null,

    -- 事件类型（建议用 smallint，在代码里枚举）
    -- 示例：
    --   1=heartbeat_gap(心跳中断)  2=door_open 3=door_close
    --   10=deposit(投递)          11=weigh(称重)
    --   20=error(异常)            21=warning(告警)
    --   30=maintenance(维护)
    event_type  smallint    not null,

    -- 事件级别（可选）：1=info 2=warn 3=error 4=critical
    severity    smallint    not null default 1,

    -- 事件处理状态（可选）：1=new 2=acked 3=resolved 4=ignored
    status      smallint    not null default 1,

    -- 幂等/链路追踪 ID（可选但强烈建议）
    -- 用法：
    --   - 设备离线补报/重试时保证“同一事件不重复入库”
    --   - 也可用于跨系统串日志
    trace_id    uuid        not null default gen_random_uuid(),

    -- 扩展详情（结构易变）
    -- 示例：
    -- {
    --   "door_open": true,
    --   "weight_delta": 1.23,
    --   "baseline": 10.50,
    --   "tof_distance": 48,
    --   "error_code": "SENSOR_TIMEOUT",
    --   "raw": {...}
    -- }
    payload     jsonb       not null default '{}'::jsonb,

    -- 审计字段（由 GORM 自动维护）
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),

    -- 约束（按你需要可调整枚举范围）
    constraint event_severity_ck check (severity in (1, 2, 3, 4)),
    constraint event_status_ck check (status in (1, 2, 3, 4))
);

-- =========================================================
-- 索引设计（覆盖 90% 查询）
-- =========================================================

-- 核心：按设备 + 时间查（最近 N 条 / 时间范围）
create index if not exists event_device_occurred_at_idx
    on event (device_id, occurred_at desc);

-- 时间维度：用于按时间导出/统计/清理、后续做分区也有用
create index if not exists event_occurred_at_idx
    on event (occurred_at desc);

-- 常见筛选：按类型 + 时间（比如只看投递、只看异常）
create index if not exists event_type_occurred_at_idx
    on event (event_type, occurred_at desc);

-- 幂等：如果你希望全局唯一就用 unique(trace_id)
-- 如果你更希望“同设备内唯一”，用 unique(device_id, trace_id)
create unique index if not exists event_trace_id_uk
    on event (trace_id);
