-- =========================================================
-- 表名：heartbeat
-- 说明：
--   设备心跳表（高频时序数据）
--   用于记录设备周期性上报的状态快照
--
-- 设计原则：
--   1. 写多读少，按 device + time 查询
--   2. 不使用 uuid 作为主键，保证写入和索引友好
--   3. 不加外键约束，避免高频写入带来额外开销
--   4. created_at / updated_at 由 GORM 维护
-- =========================================================

create table if not exists heartbeat
(
    -- 内部主键
    -- 仅用于数据库内部排序 / join / 定位
    id              bigint generated by default as identity primary key,

    -- 设备 ID（逻辑外键，指向 device.id）
    -- 高频表不加 foreign key，避免锁与性能损耗
    device_id       bigint      not null,

    -- 设备实际产生心跳的时间（非常重要）
    -- 与 created_at 不同，用于：
    --   - 离线补报
    --   - 网络抖动排查
    --   - 真实时间线分析
    reported_at     timestamptz not null,

    -- 信号强度（如 RSSI / 网络质量）
    -- 具体含义由设备侧约定
    signal_strength smallint,

    -- 电量百分比（0 ~ 100）
    -- 若为市电设备可为空
    battery_level   smallint,

    -- 扩展状态负载（高频、结构易变）
    -- 示例：
    -- {
    --   "door_open": false,
    --   "weight": 12.34,
    --   "tof_distance": 48,
    --   "error_codes": ["SENSOR_TIMEOUT"]
    -- }
    payload         jsonb       not null default '{}'::jsonb,

    -- 审计字段
    -- 注意：
    --   - default 由数据库提供
    --   - 实际更新时间由 GORM 自动维护
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- =========================================================
-- 索引设计
-- =========================================================

-- 最核心索引：
-- 按设备 + 时间范围查询 / 最近 N 条
create index if not exists heartbeat_device_reported_at_idx
    on heartbeat (device_id, reported_at desc);

-- 时间维度索引：
-- 用于排障、统计、清理、后期分区迁移
create index if not exists heartbeat_reported_at_idx
    on heartbeat (reported_at desc);
