create table heartbeat
(
    id          bigint generated by default as identity
        primary key,
    device_id   bigint                                       not null,
    reported_at timestamp with time zone,
    meta        jsonb                    default '{}'::jsonb not null,
    created_at  timestamp with time zone default now()       not null
);

create index heartbeat_device_reported_at_idx
    on heartbeat (device_id asc, reported_at desc)
    where reported_at is not null;

create index heartbeat_device_created_at_idx
    on heartbeat (device_id asc, created_at desc);

